
version: '2'
services:
  db:
    image: postgres:9.4
    volumes:
      - ./dbdata:/Mac/var/lib/postgresql/data
  web:
    build: 
      context: ./lukather-discography
    command: bash start_server.sh
    ports:
      - "8080:8080"
    volumes:
      - ./lukather-discography:/usr/src/app
    working_dir: /usr/src/app
  api:
    build:
      context: ./lukather-api
    command: bash /app/start_server.sh
    environment:
      RAILS_PORT: 3000
      DB_HOST: db
      DB_USERNAME: postgres
    volumes:
      - ./lukather-api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
