version: '2'
services:
  web:
    build: 
      context: ./lukather-discography
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./lukather-discography:/usr/src/app
    working_dir: /usr/src/app
