version: '2'
services:
  db:
    image: postgres:9.4
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  api:
    build:
      context: .
    command: bash /apps/lukather-api/start_server.sh
    environment:
      RAILS_PORT: 3000
      DB_HOST: db
      DB_USERNAME: postgres
    volumes:
      - .:/apps/lukather-api
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build: .
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./:/apps/lukather-discography/src/app
    working_dir: /apps/lukather-discography/src/app
